version: "3.8"
services:
  api:
    build:
      context: .
    container_name: norm_plov_api_container
    restart: always
    ports:
      - "3300:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@136.228.158.126:3299/postgres
    depends_on: []
    volumes:
      - ./uploads:/app/uploads
