services:
  api:
    build:
      context: .
    container_name: norm_plov_api_container
    restart: always
    ports:
      - "8000:8000"  
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@34.142.183.32:5433/fastapi
    depends_on: []